export interface WordEntry {
  word: string;
  definition: string;
}

export const WORD_BANK: Record<string, WordEntry[]> = {
  beginner: [
    { word: "apple", definition: "Noun: A round fruit, typically red or green" },
    { word: "train", definition: "Noun: A series of connected vehicles on a track" },
    { word: "brave", definition: "Adjective: Ready to face danger; courageous" },
    { word: "cloud", definition: "Noun: A visible mass of water vapor in the sky" },
    { word: "dream", definition: "Noun: A series of images experienced during sleep" },
    { word: "flame", definition: "Noun: The visible part of a fire; a tongue of fire" },
    { word: "giant", definition: "Noun: An imaginary being of extraordinary size and strength" },
    { word: "heart", definition: "Noun: The organ that pumps blood through the body" },
    { word: "light", definition: "Noun: Electromagnetic radiation visible to the human eye" },
    { word: "magic", definition: "Noun: The power of influencing events by mysterious forces" },
    { word: "night", definition: "Noun: The period of darkness between sunset and sunrise" },
    { word: "ocean", definition: "Noun: A vast expanse of salt water covering the earth" },
    { word: "plant", definition: "Noun: A living organism that grows in soil and makes food from sunlight" },
    { word: "queen", definition: "Noun: A female monarch or the wife of a king" },
    { word: "river", definition: "Noun: A large natural stream of water flowing to the sea" },
    { word: "smile", definition: "Noun: A facial expression of pleasure showing the teeth" },
    { word: "tiger", definition: "Noun: A large wild cat with orange and black stripes" },
    { word: "voice", definition: "Noun: Sound produced in a person's larynx when speaking" },
    { word: "water", definition: "Noun: A clear liquid essential to all forms of life" },
    { word: "world", definition: "Noun: The earth and all the people and things on it" },
    { word: "storm", definition: "Noun: A violent disturbance of the atmosphere with thunder" },
    { word: "stone", definition: "Noun: A hard solid mineral matter; a piece of rock" },
    { word: "horse", definition: "Noun: A large four-legged animal used for riding" },
    { word: "bread", definition: "Noun: A food made of flour, water, and yeast baked in an oven" },
    { word: "green", definition: "Adjective: The color of grass and leaves; between blue and yellow" },
  ],
  intermediate: [
    { word: "rhythm", definition: "Noun: A strong, regular, repeated pattern of sound or movement" },
    { word: "bicycle", definition: "Noun: A vehicle with two wheels driven by pedaling" },
    { word: "ceiling", definition: "Noun: The upper interior surface of a room" },
    { word: "foreign", definition: "Adjective: Relating to or coming from another country" },
    { word: "ancient", definition: "Adjective: Belonging to the very distant past; very old" },
    { word: "believe", definition: "Verb: To accept as true; to have faith or confidence in" },
    { word: "captain", definition: "Noun: The person in command of a ship, aircraft, or team" },
    { word: "dolphin", definition: "Noun: A small, highly intelligent social marine mammal" },
    { word: "episode", definition: "Noun: An event forming part of a sequence; a single TV program" },
    { word: "freedom", definition: "Noun: The power or right to act, speak, or think as one wants" },
    { word: "genuine", definition: "Adjective: Truly what something is said to be; authentic" },
    { word: "horizon", definition: "Noun: The line at which the earth and sky appear to meet" },
    { word: "innocent", definition: "Adjective: Not guilty of a crime or offense; free from sin" },
    { word: "journey", definition: "Noun: An act of traveling from one place to another" },
    { word: "million", definition: "Noun: The number equal to one thousand thousands; 1,000,000" },
    { word: "neutral", definition: "Adjective: Not supporting either side in a conflict; impartial" },
    { word: "patient", definition: "Adjective: Able to wait calmly for a long time without annoyance" },
    { word: "penguin", definition: "Noun: A flightless seabird of the Southern Hemisphere" },
    { word: "whistle", definition: "Verb: To make a clear high-pitched sound by forcing breath" },
    { word: "wrinkle", definition: "Noun: A small line or crease in a surface or the skin" },
    { word: "absence", definition: "Noun: The state of being away from a place or person" },
    { word: "address", definition: "Noun: The particulars of where someone lives or works" },
    { word: "acquire", definition: "Verb: To buy or obtain something for oneself" },
    { word: "assault", definition: "Noun: A physical attack; a sudden violent attack" },
    { word: "balloon", definition: "Noun: A small rubber bag inflated with air, used as a toy" },
  ],
  expert: [
    { word: "accommodate", definition: "Verb: To provide lodging or sufficient space for; to adapt" },
    { word: "bureaucracy", definition: "Noun: A system of government with complex rules and procedures" },
    { word: "conscience", definition: "Noun: An inner sense of right and wrong guiding one's actions" },
    { word: "exaggerate", definition: "Verb: To represent something as larger or more extreme than it is" },
    { word: "fahrenheit", definition: "Noun: A temperature scale where water freezes at 32 degrees" },
    { word: "guarantee", definition: "Noun: A formal promise or assurance that conditions will be fulfilled" },
    { word: "hypocrisy", definition: "Noun: The practice of claiming higher standards than one follows" },
    { word: "illiterate", definition: "Adjective: Unable to read or write; uneducated in a subject" },
    { word: "lieutenant", definition: "Noun: A military officer of relatively junior commissioned rank" },
    { word: "maintenance", definition: "Noun: The process of preserving something in good condition" },
    { word: "occurrence", definition: "Noun: An incident or event that takes place; the frequency of happening" },
    { word: "perseverance", definition: "Noun: Continued effort despite difficulty, delay, or failure" },
    { word: "surveillance", definition: "Noun: Close observation, especially of a suspected person or place" },
    { word: "thoroughly", definition: "Adverb: In a complete and careful manner; fully; entirely" },
    { word: "unconscious", definition: "Adjective: Not conscious; not aware of one's surroundings" },
    { word: "vulnerable", definition: "Adjective: Susceptible to physical or emotional attack or harm" },
    { word: "Wednesday", definition: "Noun: The day of the week between Tuesday and Thursday" },
    { word: "privilege", definition: "Noun: A special right or advantage available only to particular people" },
    { word: "necessary", definition: "Adjective: Required to be done; essential; indispensable" },
    { word: "discipline", definition: "Noun: The practice of training to obey rules or a code of behavior" },
    { word: "millennium", definition: "Noun: A period of one thousand years; the year 2000 and beyond" },
    { word: "embarrass", definition: "Verb: To cause someone to feel self-conscious or awkward" },
    { word: "committee", definition: "Noun: A group of people appointed to perform a function" },
    { word: "correspond", definition: "Verb: To have a close similarity; to communicate by letter" },
    { word: "desperate", definition: "Adjective: Feeling or showing a hopeless sense that a situation is bad" },
  ],
  olympiad: [
    { word: "logorrhea", definition: "Noun: A tendency to extreme talkativeness and incoherent verbal outpouring" },
    { word: "schadenfreude", definition: "Noun: Pleasure derived by someone from another person's misfortune" },
    { word: "psoriasis", definition: "Noun: A skin disease marked by red, itchy, scaly patches on the skin" },
    { word: "mnemonic", definition: "Noun: A device or pattern that aids memory, such as a rhyme or acronym" },
    { word: "phlegmatic", definition: "Adjective: Having a calm, stoic temperament; not easily excited or angered" },
    { word: "onomatopoeia", definition: "Noun: Words that imitate the sound they describe, such as buzz or sizzle" },
    { word: "archipelago", definition: "Noun: A group of islands clustered together in a sea or ocean" },
    { word: "chrysanthemum", definition: "Noun: A plant of the daisy family with brightly colored double flowers" },
    { word: "soliloquy", definition: "Noun: An act of speaking thoughts aloud when alone, as in a play" },
    { word: "sacrilegious", definition: "Adjective: Treating something sacred with great disrespect or irreverence" },
    { word: "supercilious", definition: "Adjective: Behaving as though one is superior to others; disdainful" },
    { word: "perspicacious", definition: "Adjective: Having a ready insight; shrewd; having sharp mental perception" },
    { word: "obstreperous", definition: "Adjective: Noisy and difficult to control; boisterously defiant" },
    { word: "vicissitude", definition: "Noun: A change of circumstances or fortune, typically unwelcome" },
    { word: "loquacious", definition: "Adjective: Tending to talk a great deal; garrulous; very talkative" },
    { word: "ephemeral", definition: "Adjective: Lasting for a very short time; transitory; short-lived" },
    { word: "tintinnabulation", definition: "Noun: A ringing or tinkling sound, as of a bell or bells" },
    { word: "bourgeois", definition: "Adjective: Relating to the middle class; preoccupied with material values" },
    { word: "diphtheria", definition: "Noun: An acute and highly contagious bacterial disease of the throat" },
    { word: "idiosyncrasy", definition: "Noun: A mode of behavior peculiar to an individual; a distinctive quirk" },
    { word: "pusillanimous", definition: "Adjective: Showing a lack of courage or determination; faint-hearted" },
    { word: "sesquipedalian", definition: "Adjective: Given to using long words; a long word itself" },
    { word: "verisimilitude", definition: "Noun: The appearance of being true or real; plausibility" },
    { word: "concatenation", definition: "Noun: A series of linked things; the action of linking things together" },
    { word: "surreptitious", definition: "Adjective: Kept secret, especially because it would be disapproved of" },
  ],
};

export function getRandomWord(difficulty: string): WordEntry {
  const bank = WORD_BANK[difficulty] ?? WORD_BANK.beginner;
  return bank[Math.floor(Math.random() * bank.length)];
}
